# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "M3YTKyN+2uD9lBhNEoNwrmUZ9OsiO4KrPWWFinro3VHyilUBK4TfRDYJJUw1kedFFOE0qEAbSQT6SANmNTKewZwQl9+Q3URvWiURMGzUDqI7LAZXjO3cd3Y7XwX1UJ5cENmH8+rkp2N3+mPxjf2DEICE8Lu+Ic/GedcHZGRNJFVWNIdWxIM4IeQ+VBmXJNeNfsqKX7ieRqdVUNpYq261mSFAQZDszslCjjyZoEsyeYK1/Fv7NjLT0pyFLUJvbdA0Ah7HxHp7uus1JtBPEb3jQIVe7urwL21ZwRxnSvOn9YmKr7mOwx4YnhDzapnB1eFBkYNb3gFFGRuG1oZpUmIUjTQDZKUQXKxMw69k5fPD+U6KHZMmNdb3GyFtjkd0sTnC8q17n0C2ZFNhoVzFnUt6Os4FkBdyZ/byfLBWE6pdjdtAexglJzHaXshn2/YK2W+2mq2JOBnVWCvRPrSCPDpLhjIOMMog1Tx3oMmx2I32bnn5N6BvR9qWCUxqGQZsjYa5Mj9aIod74A7e6UkHWZhH8b2L/IKsPwraeVCpx8Gpx8h1GgSyYWCgFPsmPtkOWOtfPh30mRQra7S1cYGoWb7Pyd4PZVfDvnpiPA+jUlE1Nh1Fh2VEwax508+BxugUCJLi32UHtUdML6d3f+iMd21pkR4F4rt60XDmp3qXiLN4nUU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
