travis:
  secure:
    BINSTAR_TOKEN: Aep9TjICbk8CdWE4D0EMgu0WQB4o30V0IKhpqptKT3Csfp6illVc+qN97Bf0ls0jMCzijmiY63gu0lJkiq3oyu/q14cY2MhxTLhN/2uf5ZYsK1R8hUBof/ZjprWoIaQMyGjdYI7F5EFLgxfQilpIbvG7AhZrfREk3TGNzJsMtJrojGTJg7Heg9YtrsbIRBB520RVceZYsdLRy44oI0yuHrEieaTkMKde576OvSz78I0NsHHlIap2XPyEyrcHXC7JRqAGyRosNUTBilynSPMSxUtjRT/EEkmpL7cL7QyZjc5QCLaclBlHBG9dqr/hVp1QRTMGpwmQTtjVE4Ig31PMcOXLy+eoeGrduvi+65BIcJFBG9ipKc9L4X1298+LOANvgZpj8Ocasng+e1tGCj1w1m75HfJH7udaIOTz6k6TvZStkXFjKS/VGQTsKlvurhnLMjGn7zjFJ3wFLaTJkdGneytuanZcZ1JPZ1ggHC35DNwM+xLq8eRWRHUTud20C4wuK933h5Z0QLEhQpBlaj+5Ghzf7k4Y83XG/3WkmfkRoB/H/LMw8I30qZnXuoUBN7N2ZpWziSr99v4lqF5YGrzJF69OSKTtaX9k5Nj5peNQU0MD9tNLgSFrZi5uKMmSwWsEOhIWZTIQSlMXJaQ2SWZVxegoBj8HRQxq2QG2RJ6+SWQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
