travis:
  secure:
    BINSTAR_TOKEN: LsJTBL57H+ErewYDrtxvEYi6RL5xx3oiZDQr7XQarIEeAGXs1ACvuld7kiKPoQUnFfCzjB533HGfZKuBh3lqHZK9C+V3edGNADfcVTNMSk7BY4PM0fR3ywXN9raAgrQLEdWex7p9ruVwOOdosUU8YE4GE+iD8/U3eaPSpf5Ft2S3ICYjZ2N4D3d1DDlBaetgQ0u+qKytxvK92WDlxPr3J0vsBITo9zswpHE9MHEYGBM10rBipZwq5x5JCLRGahJBl8ViguoCHzV86InVM/tLwA2NKIFb3XcoThLML82mxhH2VnXIcafZQ+UH0fIUMbSoK4IjdfeQwDiBDF/gfyy6yDZnuYtUAm/q5qkLnuddvuNsk+d0bGUZkLVCz9VOqRa7Y0FOvGexAfF0KaJQD9qRGnhqtMkHLL0/dEd6CrnNb3guiBaAbKxG3MWDMAxKxRpuU6cFDv2kL7CL6NvogNJZ3Ru4YQMUijhbCLGyhcfBzN+5C+a5DQ7qyvbWhCeMKtdw/MFa7ZbNh5C/TyN4ONocZcY3jbwGdVktgTWKalLBw1/epH8eqps497Q3HvkTSE5zDX87Jp9f92HwmsKZhqLwFGyjN429H9eyMdvU7ASnCypUg9uSdUcy4xC7L0yf4H8bGrV3WnO364v4dYBgV5GLLTAcgKPKCVNNGiXGyIPMFQg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
