travis:
  secure:
    BINSTAR_TOKEN: OF7RplORNbUN/YvRL97vR2V3WHAQoHQJLI2tAafKIghaDpMqO4ZlHqT9kf2y8/wEOeBKnbMJ0IbhucF7+kvMOazAbgjApLUvYBuJhPQ9fxSjweAr5+ncNW6eBFp/E1m6eKwBaKVLhcjeQYop2zYsm/iNMpO5exXHcZxpqKUaoDL1EHHjEDFlLlgKzOzCnXaX51tesu8Lz1b+Ptd8KBu3JCbDpiin0OFwrtIzV/ebpZbXqBnXOJLDwIpxFOsIpbDkMA+qs5aShxa+axqOpDZh91ipaR+lfyxFSHuQzYKETxymv+gXRW6eghtX6Q7lUqi4PwNSon1l87BhOstzJyNbxx5CRMC9HC5vVQG1q5hzPEPdkyFx8Iue0yVFUx0WtxxbL54Ya6DZqYNN/PdSpYi6dgPKQ3VqMrfrsCgfB+XnYjM/y12DBWTOlWIlP4qyqZnsJqLY16Ur2UTqq+aXJeiqQqFt8sOYwEwk+sSQIJZsSuhUr6tWXloczPH6c28knGvjztL2zNEgnmvSWmcz4/6Vaf3589V6QPAs8ZTExhbTulcPQBNBOvlP+gg/teQK4Ubo9+RAfRmXhQ4q5BPtc3CtMe9iW/ohCcfWFsFeDcc7D6ck6rBGZEWdxlCmmmuEdLDOGNEL7g7uOTnlgtr7ek2sRxCWzfGYqw13BT6+qMhLiT0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
