travis:
  secure:
    BINSTAR_TOKEN: Ko/y9YbQqjLkdzsG2hd/pqrdzhKrLlyghG8elM6btCuwS5r35k3xHmPu8NAxF8+CREb8HZ5fboaK9jZPBebthbZSBO3loociUME470O99UI+zLljA5zmMj0wKXC4kb7dWLanUfMBJE3eW3hF25sYh6BX4N3+WRAho1az0nrinNIwcs3DE//rRYV2bzSLxTrTvOQTC5iZHwmUTPwp3ixGb1LnOB0QJfnnSa5u8dcFvCJvzMNDwORNuw8DmB1l9G8EB0w0eUUDM99aoNrrrsRBmDYkXUDYGOdOt1BWoQPhLeixEhE8w/7wEKKgnRbepYM460fcmvws00idHGrKAr76yithhoE1685VdG6OLR4lt7E9Sv8ckg3XG0/Me2Y8+NZ7sQMmunRwUaHgUjg/cz1lg+GnRCEK7gKd65B9CUwm1MzeevJi9Ad1rrDkqCvkXrYVGjKACHuWDWgDkY5BoWuliZr/j3PEaFf2akPKMh2qHIoNVSyymZ0dI0c6nYGfL3tqQpyPLryKQJzeNRd6unlaCwMm1CVWReBG840CBpW4KXex7uvIGuajqNRWOuyrdQrR2oS3Fzu2wAcbB+QgLDYifpgh8zhOk6WfEqZimKsNDYJPKoymcWhaffZj8L12DDMdpt+JbVE76Z1DB6NlS0rV0BZr7QfGkuHtHSGUD6GQvnY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
