travis:
  secure:
    BINSTAR_TOKEN: M3YTKyN+2uD9lBhNEoNwrmUZ9OsiO4KrPWWFinro3VHyilUBK4TfRDYJJUw1kedFFOE0qEAbSQT6SANmNTKewZwQl9+Q3URvWiURMGzUDqI7LAZXjO3cd3Y7XwX1UJ5cENmH8+rkp2N3+mPxjf2DEICE8Lu+Ic/GedcHZGRNJFVWNIdWxIM4IeQ+VBmXJNeNfsqKX7ieRqdVUNpYq261mSFAQZDszslCjjyZoEsyeYK1/Fv7NjLT0pyFLUJvbdA0Ah7HxHp7uus1JtBPEb3jQIVe7urwL21ZwRxnSvOn9YmKr7mOwx4YnhDzapnB1eFBkYNb3gFFGRuG1oZpUmIUjTQDZKUQXKxMw69k5fPD+U6KHZMmNdb3GyFtjkd0sTnC8q17n0C2ZFNhoVzFnUt6Os4FkBdyZ/byfLBWE6pdjdtAexglJzHaXshn2/YK2W+2mq2JOBnVWCvRPrSCPDpLhjIOMMog1Tx3oMmx2I32bnn5N6BvR9qWCUxqGQZsjYa5Mj9aIod74A7e6UkHWZhH8b2L/IKsPwraeVCpx8Gpx8h1GgSyYWCgFPsmPtkOWOtfPh30mRQra7S1cYGoWb7Pyd4PZVfDvnpiPA+jUlE1Nh1Fh2VEwax508+BxugUCJLi32UHtUdML6d3f+iMd21pkR4F4rt60XDmp3qXiLN4nUU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
