travis:
  secure:
    BINSTAR_TOKEN: HJlegSDb/IY8i4x1TFbWV5QBSLPKCWXh5wUXBYBRbf5hmwwQmr5MqEo8AFPCtQeBOOCY842EdkgszwcxFd2J8Eo8cZGM8zgzpL0k3aUbC/CT93+7zPpzMsxcQoL2BRqq5wYBlLMTaVBCdyqdDrujzn7QEHZ4LZAUgEMzjnRkqE1P8VzE7d841AIfPSOnBTdlTlWr4Np8h+r/i/jgyGDg8N8DA+1LApxlsOSLtbdnxs+XQV+ghm9Cg2ovg+LnO8TNvx66qa6U2jM8chJrJoMHhBhBMpUUuQ6iPVKyUTG8GBaN2ODLQQxq3BBGFKitDa4waHfzBGX6iOe+hLWtTbIrn0TcPhcrWeQhENn16Nq3EDxxZEha7ZrfjFQ5+oYbktgD045K7uyGxAr23EYUm/Kx5XNllQItsMzIVgNrYHqGals98WUd77WNpAy8v6/gphjqVEKeWJFoAWI02qt10rKHtwfY15AvStXBEYp2zLMVsASdYIVjiQiu3lXyjXHAUQFPLDsiKmPfoFTdFjteimIiEZbwVOfnCCxyjALgbvg3FsV5UDt7kG8D973M7mFae1EMcN5x044PUxWvpPYCiFrFRXtDORX1h1kvTyEBXKhidYq2JTJuH4eavtAMUBGFLl3KscCIb55fH1fm3eM6m05Zis2jEJtrrOqPWKHsAzyWqh0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
